course_project_group_3/accounts/urls.py
from django.urls import path, include

from .views import SignUpView

from accounts import views

app_name = 'accounts'  # ensure this line is here, the value should match the namespace you used in the main urls.py

urlpatterns = [
    path('', views.landing_page, name='landing_page'),
    path('accounts/', views.wallet, name='wallet'),
    path('login/', views.login_user, name='login_user'),
    path('profile/', views.profile, name='profile'),
    path('register/', views.membership, name='register'),
    path('settings/', views.settings, name='settings'),
    path('logout/', views.logout_view, name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'),  # django will match this to 'dash:dashboard'

    # Transaction URLs
    path('create_deposit_transaction/', views.create_bank_transaction, name='create_bank_transaction'),
    path('create_new_account/', views.membership, name='membership'),

    # Account URLs
    path('create_bank_account/', views.create_bank_account, name='create_bank_account'),

#     TODO: Add URL to generate report (Curtis)
    path('generate_report/', views.generate_report, name='generate_report'),
    path('generate_report/', views.generate_pdf_report, name='generate_pdf_report'),
    path('generate_report/', views.generate_csv_report, name='generate_csv_report')]

course_project_group_3/course_project_group_3/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [

    path('admin/', admin.site.urls),

    # accounts/
    path('', include('accounts.urls')),
    # path('accounts/', include('django.contrib.auth.urls')),
    # path("", TemplateView.as_view(template_name="home.html"), name="home"),
]

course_project_group_3/accounts/forms.py
import random
import string
from urllib import request

from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from accounts.models import UserSetting, BankAccount


class CustomUserCreationForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=True)
    last_name = forms.CharField(max_length=30, required=True)
    email = forms.EmailField(max_length=254)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2',)


def generate_unique_account_number():
    digits = string.digits  # String containing digits (0-9)
    account_number = ''.join(random.choice(digits) for _ in range(8))
    while BankAccount.objects.filter(account_number=account_number).exists():
        account_number = ''.join(random.choice(digits) for _ in range(8))
    return int(account_number)


# def create_user(self, username, email, password, **extra_fields):
#     user = super().create_user(username, email, password, **extra_fields)
#     # Create a user setting and bank account for the new user
#     settings = UserSetting.objects.create(user=user)
#     settings.save()
#     account = BankAccount.objects.create(account_number=generate_unique_account_number())
#     account.save()
#
#     return user

#formatting the fields for the form
class AccountModelChoiceField(forms.ModelChoiceField):
    def label_from_instance(self, obj):
        return f"{obj.user.username}'s {obj.account_type} Account ({str(obj.account_number)[-4:]})"

class SpendingLimitForm(forms.Form):
    account = AccountModelChoiceField(
        queryset=BankAccount.objects.all(), 
        widget=forms.Select(attrs={'class': 'form-control account-select'}), 
        empty_label=None, 
        to_field_name='account_number', 
        label='Account'
    )
    spending_limit = forms.DecimalField(
        max_digits=10, 
        decimal_places=2,
        widget=forms.NumberInput(attrs={'class': 'form-control'})
    )


    def __init__(self, user, *args, **kwargs):
        super(SpendingLimitForm, self).__init__(*args, **kwargs)
        self.fields['account'].queryset = BankAccount.objects.filter(user=user)

course_project_group_3/accounts/views.py
import csv
from datetime import datetime
from enum import member
import io
from msilib import Table
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Spacer, Paragraph
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.pagesizes import letter
from django.http import HttpResponse, FileResponse
import io
import csv
from .models import Transaction, BankAccount
from .models import Transaction
from django.contrib.auth import authenticate
from django.contrib.auth.decorators import login_required
from django.http import FileResponse, HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.contrib.auth.models import User
from django.views import generic
from django.views.decorators.http import require_POST
from psycopg2 import IntegrityError

from .forms import CustomUserCreationForm, SpendingLimitForm, generate_unique_account_number
from django.contrib import messages  # for messages
from django.contrib.auth import authenticate, logout, login

from .models import Transaction, BankAccount, UserSetting
from django.utils.crypto import get_random_string
from django.core.exceptions import ValidationError, ObjectDoesNotExist
from decimal import Decimal

from django.db.models.signals import post_save
from django.conf import settings
import logging
from reportlab.lib import colors
from reportlab.platypus import Spacer
from reportlab.pdfgen import canvas
from reportlab.lib.units import inch
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Table
from reportlab.platypus import TableStyle
from reportlab.lib.styles import getSampleStyleSheet
from django.views.decorators.http import require_POST
import io
import csv
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from django.http import HttpResponse, FileResponse
from .models import Transaction, BankAccount
from django.views.decorators.http import require_POST
import re
import json

from django.utils import timezone
from django.contrib.auth.models import User
from datetime import datetime
from dateutil.relativedelta import relativedelta


logger = logging.getLogger(__name__)  # Set up basic logging


# Create your views here.


class SignUpView(generic.CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy("login")
    template_name = "registration/signup.html"


def base(request):
    member = request.user
    context = {'member': member}
    return render(request, 'accounts/base.html', context)


# Will serve as the landing page for unauthenticated users
def landing_page(request):
    member = request.user
    context = {'member': member}
    return render(request, 'accounts/home.html', {'member': member})


def dashboard(request):
    user = request.user
    user_settings = UserSetting.objects.get(user=request.user)
    bank_accounts = BankAccount.objects.filter(user=request.user)
    monthly_income = user_settings.monthly_income
    annual_income = monthly_income * 12
    accounts = [{'id': account.id, 'last_four': str(account.account_number)[-4:]} for account in bank_accounts]

    form = SpendingLimitForm(request.user)

    total = 0

    #Check if budget account has been set
    if user_settings.budget_account is not None:
        
        #check if there are any transactions in the budget account
        if Transaction.objects.filter(account=user_settings.budget_account).count() != 0:

            for transaction in Transaction.objects.filter(account=user_settings.budget_account, transaction_type='withdrawal'):
                total += transaction.amount

            percent = total / user_settings.budget_account.spending_limit
            percent = percent * 100
            
    else:
        percent = 0







    # #Creating test transactions to check if the chart works
    # # Fetch the user
    # user = User.objects.get(username='jerry')  # replace 'username_here' with the actual username
    # first_account = user.bank_accounts.first()

    # # Get the current date
    # now = timezone.now()

    # # Create transactions for the past three months
    # for months_ago in range(3, 0, -1):
    #     # Calculate the date for the required number of months ago
    #     date = now - relativedelta(months=months_ago)
    #     # Set the date to the first day of the month
    #     date = date.replace(day=1, hour=0, minute=0, second=0, microsecond=0)

    #     # Create the transaction
    #     transaction = Transaction(account=first_account, transaction_type='withdrawal', timestamp=date, amount=50.0)
    #     transaction.save()

    #     print(transaction.timestamp)















    #Add spending limit form
    if request.method == 'POST':
        form = SpendingLimitForm(request.user, request.POST)
        if form.is_valid():
            account = form.cleaned_data['account']
            account.spending_limit = form.cleaned_data['spending_limit']
            user_settings.budget_account = account
            user_settings.save()
            account.save()
            return redirect('accounts:dashboard')
    else:
        form = SpendingLimitForm(request.user)

    #Creating values for charts
    labels = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
    data = []  # Initialize an empty list to store the sum of transactions for each month

    current_year = timezone.now().year

    withdrawal_transactions = []
    for month in range(1, 13):
        transactions = Transaction.objects.filter(account__user=user,transaction_type='withdrawal', timestamp__year=current_year, timestamp__month=month)
        withdrawal_transactions.extend(transactions)

        if transactions.exists():
            # Calculate the sum of transactions for the current month
            month_sum = sum(transaction.amount for transaction in transactions)
            data.append(month_sum)
        else:
            data.append(0)
    
    data = [float(x) for x in data]

    #Convert data to json to pass to template
    data = json.dumps(data)
    labels = json.dumps(labels)


    context = {
        'member': user,
        'settings': user_settings,
        'monthly_income': monthly_income,
        'annual_income': annual_income,
        'accounts': accounts,
        'form': form,
        'percent': percent,
        'labels': labels,
        'data': data
    }

    return render(request, 'accounts/dashboard.html', context)



# def dashboard(request):
#     monthly_income = 2000
#     annual_income = monthly_income * 12
#     member = request.user
#     return render(request, 'accounts/dashboard.html', {'member': member, 'monthly_income': monthly_income, 'annual_income': annual_income})


@require_POST
def generate_report(request):
    report_type = request.POST.get('reportType')

    if report_type == 'pdf':
        print('Generating PDF report')
        return generate_pdf_report(request)
    elif report_type == 'csv':
        print('Generating CSV report')
        return generate_csv_report(request)
    else:
        print('Invalid report type selected. Please try again.')
        return HttpResponse("Invalid report type selected. Please try again.")

def generate_pdf_report(request):
    user = request.user # Get the user object from the request
    logger.info(f'Generating a PDF report for user: {user.username}')
    print(f'Generating a PDF report for user: {user.username}') # Log the user generating the report
    
    transactions = Transaction.objects.filter(account__user=user)
    logger.info(f'User has {len(transactions)} transactions')    
    print(f'User has {len(transactions)} transactions') # Log the number of transactions

    # Predefined expense categories with associated keywords/patterns
    expense_categories = {
        'Groceries': ['grocery', 'supermarket'],
        'Dining': ['restaurant', 'cafe', 'food'],
        'Transportation': ['gas', 'fuel', 'car'],
        'Utilities': ['electricity', 'water', 'utility'],
        'Shopping': ['shopping', 'store'],
        'Other': ['subscription', 'pharmacy', 'haircut', 'salon', 'auto', 'repair'],  # Add other categories
    }
    # Preprocess transaction descriptions
    def preprocess_description(description):
        description = description.lower()
        description = re.sub(r'[^\w\s]', '', description)  # Remove punctuation
        
        for category, keywords in expense_categories.items():
            for keyword in keywords:
                if keyword in description:
                    return category
        return 'Other'  # Default category if no match found
    
    # Create a buffer to hold the PDF content
    buffer = io.BytesIO()
    print('Buffer created')
    
    # Create a PDF document
    doc = SimpleDocTemplate(buffer, pagesize=letter)
    elements = []
    print('PDF document created')
    
    # Add document title
    styles = getSampleStyleSheet()
    report_title = Paragraph('Transaction Report', styles['Title'])
    elements.append(report_title)
    logger.info('Added document title')
    elements.append(Spacer(1, 24))

    # Add company data section
    company_info = [
        ('Heritage Banking'),
        ('123 Here Street'),
        ('Greenville, NC 27834'),
        ('info@xyzinc.com')
    ]
    company_data = "<br/>".join([f"<b>{value}</b>" for value in company_info])
    company_info_paragraph = Paragraph(company_data, styles['Normal'])
    elements.append(company_info_paragraph)
    logger.info('Added company data section')
    elements.append(Spacer(1, 24))
    print('Company data section added')

    # Add customer data section
    customer_info = [
        ('Customer Name:', f'{user.first_name} {user.last_name}'),

course_project_group_3/accounts/templates/accounts/login.html
{% extends 'accounts/base.html' %}
{% load static %}

{% block title %}Login{% endblock %}

{% block head %}
<!--<link rel="stylesheet" href="{% static 'css/dash/wallet.css' %}">-->
{% endblock %}

{% block stylesheets %}
{% endblock %}

{% block style %}
{% endblock %}

{% block content %}
<div class="container">
        <div class="row justify-content-center">
            <div class="col-md-9 col-lg-12 col-xl-10">
                <div class="card shadow-lg o-hidden border-0 my-5">
                    <div class="card-body p-0">
                        <div class="row">
                            <div class="col-lg-6 d-none d-lg-flex">
                                <div class="flex-grow-1 bg-login-image" style="background-image: url(https://images.unsplash.com/photo-1517423568366-8b83523034fd?q=80&w=1935&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D);"></div>
                            </div>
                            <div class="col-lg-6">
                                <div class="p-5">
                                    <div class="text-center">
                                        <h4 class="text-dark mb-4">Welcome Back!</h4>
                                    </div>
                                    <form class="user">
                                        {% csrf_token %}
                                        <div class="mb-3"><input class="form-control form-control-user" type="email" id="exampleInputEmail" aria-describedby="emailHelp" placeholder="Enter Email Address..." name="email"></div>
                                        <div class="mb-3"><input class="form-control form-control-user" type="password" id="exampleInputPassword" placeholder="Password" name="password"></div>
                                        <div class="mb-3">
                                            <div class="custom-control custom-checkbox small">
                                                <div class="form-check"><input class="form-check-input custom-control-input" type="checkbox" id="formCheck-1"><label class="form-check-label custom-control-label" for="formCheck-1">Remember Me</label></div>
                                            </div>
                                        </div><button class="btn btn-primary d-block btn-user w-100" type="submit">Login</button>
                                        <hr><a class="btn btn-primary d-block btn-google btn-user w-100 mb-2" role="button"><i class="fab fa-google"></i>&nbsp; Login with Google</a><a class="btn btn-primary d-block btn-facebook btn-user w-100" role="button"><i class="fab fa-facebook-f"></i>&nbsp; Login with Facebook</a>
                                        <hr>
                                    </form>
                                    <div class="text-center"><a class="small" href="forgot-password.html">Forgot Password?</a></div>
                                    <div class="text-center"><a class="small" href="register.html">Create an Account!</a></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}
{% endblock %}

course_project_group_3/accounts/templates/accounts/membership.html
{% extends 'accounts/base_2.html' %}
{% load static %}

{% block title %}Heritage{% endblock %}

{% block head %}
{% endblock %}

{% block stylesheets %}
{% endblock %}
<!--<head>-->
<!--    <meta charset="utf-8">-->
<!--    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">-->
<!--    <title>Contact Us - Brand</title>-->
<!--    <link rel="stylesheet" href="assets/bootstrap/css/bootstrap.min.css">-->
<!--    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat:400,400i,700,700i,600,600i&amp;display=swap">-->
<!--    <link rel="stylesheet" href="assets/css/bs-theme-overrides.css">-->
<!--    <link rel="stylesheet" href="assets/css/baguetteBox.min.css">-->
<!--    <link rel="stylesheet" href="assets/css/vanilla-zoom.min.css">-->
<!--</head>-->

{% block style %}
{% endblock %}

{% block content %}
    <section class="clean-block clean-form dark">







            <div class="container">
                <div class="block-heading">
                    <h2 class="text-info">Register &amp; Join Below !</h2>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc quam urna, dignissim nec auctor in, mattis vitae leo.</p>
                </div>
                <form method="POST" action="{% url 'accounts:membership' %}">
                    {% csrf_token %}
                    <input type="hidden" name="account_type" value="Checking">
                    <div class="mb-3"><label class="form-label" for="username">Username</label>
                        <input class="form-control" type="text" id="username" name="username" data-bs-theme="light"></div>
                    <div class="mb-3"><label class="form-label" for="password">Password</label>
                        <input class="form-control" type="password" id="password" name="password" data-bs-theme="light"></div>
                    <div class="mb-3"><label class="form-label" for="firstName">First Name</label>
                        <input class="form-control" type="text" id="firstName" name="firstName" data-bs-theme="light"></div>
                    <div class="mb-3"><label class="form-label" for="lastName">Last Name</label>
                        <input class="form-control" type="text" id="lastName" name="lastName" data-bs-theme="light"></div>
<!--                    <div class="mb-3"><label class="form-label" for="address">Address</label>-->
<!--                        <input class="form-control" type="text" id="address" name="address" data-bs-theme="light"></div>-->
                    <div class="mb-3"><label class="form-label" for="email">Email</label>
                        <input class="form-control" type="email" id="email" name="email" data-bs-theme="light"></div>
<!--                    <div class="mb-3"><label class="form-label" for="phone">Phone Number</label>-->
<!--                        <input class="form-control" type="tel"></div>-->
<!--                    <div class="mb-3"><label class="form-label" for="dob">Date of Birth</label>-->
<!--                        <input class="form-control" id="dob" type="date" name="dob"></div>-->
                    <div class="mb-3"><label class="form-label" for="monthly_income">Monthly Income</label>
                        <input class="form-control" type="number" id="monthly_income" name="monthly_income"></div>
                    <div class="mb-3"><label class="form-label" for="deposit_amount">Initial Deposit Amount</label>
                        <input class="form-control" type="number" id="deposit_amount" name="deposit_amount"></div>
                    <div class="mb-3"><label class="form-label" for="credit_score">Credit Score</label>
                        <input class="form-control" type="number" id="credit_score" name="credit_score"></div>
                    <div class="mb-3"><label class="form-label" for="profile_img_url">Profile Image URL</label>
                        <input class="form-control" type="text" id="profile_img_url" name="profile_img_url"></div>
                    <div class="mb-3"><button class="btn btn-primary" type="submit">Send</button></div>
                </form>
            </div>
        </section>
{% endblock %}

{% block scripts %}
{% endblock %}

course_project_group_3/accounts/templates/accounts/register.html
{% extends 'accounts/base.html' %}
{% load static %}

{% block title %}Heritage{% endblock %}

{% block head %}
<link rel="stylesheet" href="{% static 'bs/dash/css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'fonts/dash/Nunito.css' %}">
<link rel="stylesheet" href="{% static 'css/dash/bs-theme-overrides.css' %}">
<link rel="stylesheet" href="{% static 'css/dash/global.css' %}">
<link rel="stylesheet" href="{% static 'css/dash/wallet.css' %}">

<!--<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">-->
{% endblock %}

{% block stylesheets %}
{% endblock %}

{% block style %}
{% endblock %}

{% block content %}
<div class="container">
        <div class="card shadow-lg o-hidden border-0 my-5 mx-5">
            <div class="card-body p-0">
                <div class="row">
                    <div class="col-lg-5 d-none d-lg-flex">
                        <div class="flex-grow-1 bg-register-image" style="background-image: url(https://images.unsplash.com/photo-1517423568366-8b83523034fd?q=80&w=1935&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D);"></div>
                    </div>
                    <div class="col-lg-7">
                        <div class="p-5">
                            <div class="text-center">
                                <h4 class="text-dark mb-4">Create an Account!</h4>
                            </div>
                            <form class="user">
                                <div class="row mb-3">
                                    <div class="col-sm-6 mb-3 mb-sm-0"><input class="form-control form-control-user" type="text" id="exampleFirstName" placeholder="First Name" name="first_name"></div>
                                    <div class="col-sm-6"><input class="form-control form-control-user" type="text" id="exampleLastName" placeholder="Last Name" name="last_name"></div>
                                </div>
                                <div class="mb-3"><input class="form-control form-control-user" type="email" id="exampleInputEmail" aria-describedby="emailHelp" placeholder="Email Address" name="email"></div>
                                <div class="row mb-3">
                                    <div class="col-sm-6 mb-3 mb-sm-0"><input class="form-control form-control-user" type="password" id="examplePasswordInput" placeholder="Password" name="password"></div>
                                    <div class="col-sm-6"><input class="form-control form-control-user" type="password" id="exampleRepeatPasswordInput" placeholder="Repeat Password" name="password_repeat"></div>
                                </div><button class="btn btn-primary d-block btn-user w-100" type="submit">Register Account</button>
                                <hr><a class="btn btn-primary d-block btn-google btn-user w-100 mb-2" role="button"><i class="fab fa-google"></i>&nbsp; Register with Google</a><a class="btn btn-primary d-block btn-facebook btn-user w-100" role="button"><i class="fab fa-facebook-f"></i>&nbsp; Register with Facebook</a>
                                <hr>
                            </form>
                            <div class="text-center"><a class="small" href="forgot-password.html">Forgot Password?</a></div>
                            <div class="text-center"><a class="small" href="../../../../../../Education/Spring%2024/Software%20Project%20Management/Project/Exports/Banking_v1_03-07-24/login.html">Already have an account? Login!</a></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}
<script src="https://unpkg.com/chart.js@2.7.1/"></script>
<!--<script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.2/dist/chart.umd.min.js"></script>-->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js"></script>

{% endblock %}